name: soma
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.3.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.0.0
  intl: 0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  supabase_flutter: ^2.12.0
  flutter_webrtc: ^0.12.0
  permission_handler: ^12.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.5.4
  flutter_tts: ^4.2.5
  csv: ^6.0.0
  flutter_svg: ^2.0.10
  postgres: ^3.5.9
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  sqlite3_flutter_libs: any
  sqlite3: ^3.1.5
  just_audio: ^0.9.39
  record: ^5.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_driver:
    sdk: flutter

  supabase: any
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/avatar/
