drop extension if exists "pg_net";


  create table "public"."circle_participants" (
    "id" bigint generated by default as identity not null,
    "circle_id" uuid not null,
    "user_id" uuid not null,
    "role" text default 'player'::text,
    "score" integer default 0,
    "is_ready" boolean default false,
    "joined_at" timestamp with time zone default now()
      );


alter table "public"."circle_participants" enable row level security;


  create table "public"."circles" (
    "id" uuid not null default gen_random_uuid(),
    "host_id" uuid not null,
    "name" text not null,
    "from_lang" text not null,
    "to_lang" text not null,
    "mode" text not null,
    "level" text not null,
    "max_players" integer default 5,
    "questions_count" integer default 15,
    "time_per_q" integer default 10,
    "allow_spectators" boolean default true,
    "status" text default 'lobby'::text,
    "created_at" timestamp with time zone default now(),
    "questions" jsonb default '[]'::jsonb
      );


alter table "public"."circles" enable row level security;


  create table "public"."courses" (
    "id" text not null,
    "title" text not null,
    "subtitle" text,
    "icon_url" text,
    "source_lang" text,
    "target_lang" text
      );


alter table "public"."courses" enable row level security;


  create table "public"."friendships" (
    "id" bigint generated by default as identity not null,
    "requester_id" uuid not null,
    "addressee_id" uuid not null,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."friendships" enable row level security;


  create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "sender_id" uuid not null,
    "receiver_id" uuid not null,
    "content" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."messages" enable row level security;


  create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "type" text,
    "title" text,
    "body" text,
    "is_read" boolean default false,
    "metadata" jsonb default '{}'::jsonb,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."notifications" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "username" text,
    "display_name" text,
    "full_name" text,
    "avatar_url" text,
    "website" text,
    "bio" text,
    "location" text,
    "total_xp" integer default 0,
    "settings" jsonb default '{}'::jsonb,
    "updated_at" timestamp with time zone
      );


alter table "public"."profiles" enable row level security;


  create table "public"."sentences" (
    "id" bigint generated by default as identity not null,
    "course_id" text,
    "original" text not null,
    "translation" text not null,
    "difficulty" integer default 1
      );


alter table "public"."sentences" enable row level security;


  create table "public"."user_courses" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "course_id" text not null,
    "progress_xp" integer default 0,
    "last_accessed" timestamp with time zone default now()
      );


alter table "public"."user_courses" enable row level security;


  create table "public"."vocabulary" (
    "id" bigint generated by default as identity not null,
    "course_id" text,
    "word" text not null,
    "translation" text not null,
    "usage_example" text,
    "difficulty" integer default 1
      );


alter table "public"."vocabulary" enable row level security;

CREATE UNIQUE INDEX circle_participants_circle_id_user_id_key ON public.circle_participants USING btree (circle_id, user_id);

CREATE UNIQUE INDEX circle_participants_pkey ON public.circle_participants USING btree (id);

CREATE UNIQUE INDEX circles_pkey ON public.circles USING btree (id);

CREATE UNIQUE INDEX courses_pkey ON public.courses USING btree (id);

CREATE UNIQUE INDEX friendships_pkey ON public.friendships USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX sentences_pkey ON public.sentences USING btree (id);

CREATE UNIQUE INDEX user_courses_pkey ON public.user_courses USING btree (id);

CREATE UNIQUE INDEX user_courses_user_id_course_id_key ON public.user_courses USING btree (user_id, course_id);

CREATE UNIQUE INDEX vocabulary_pkey ON public.vocabulary USING btree (id);

alter table "public"."circle_participants" add constraint "circle_participants_pkey" PRIMARY KEY using index "circle_participants_pkey";

alter table "public"."circles" add constraint "circles_pkey" PRIMARY KEY using index "circles_pkey";

alter table "public"."courses" add constraint "courses_pkey" PRIMARY KEY using index "courses_pkey";

alter table "public"."friendships" add constraint "friendships_pkey" PRIMARY KEY using index "friendships_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."sentences" add constraint "sentences_pkey" PRIMARY KEY using index "sentences_pkey";

alter table "public"."user_courses" add constraint "user_courses_pkey" PRIMARY KEY using index "user_courses_pkey";

alter table "public"."vocabulary" add constraint "vocabulary_pkey" PRIMARY KEY using index "vocabulary_pkey";

alter table "public"."circle_participants" add constraint "circle_participants_circle_id_fkey" FOREIGN KEY (circle_id) REFERENCES public.circles(id) ON DELETE CASCADE not valid;

alter table "public"."circle_participants" validate constraint "circle_participants_circle_id_fkey";

alter table "public"."circle_participants" add constraint "circle_participants_circle_id_user_id_key" UNIQUE using index "circle_participants_circle_id_user_id_key";

alter table "public"."circle_participants" add constraint "circle_participants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."circle_participants" validate constraint "circle_participants_user_id_fkey";

alter table "public"."circles" add constraint "circles_host_id_fkey" FOREIGN KEY (host_id) REFERENCES public.profiles(id) not valid;

alter table "public"."circles" validate constraint "circles_host_id_fkey";

alter table "public"."friendships" add constraint "friendships_addressee_id_fkey" FOREIGN KEY (addressee_id) REFERENCES public.profiles(id) not valid;

alter table "public"."friendships" validate constraint "friendships_addressee_id_fkey";

alter table "public"."friendships" add constraint "friendships_requester_id_fkey" FOREIGN KEY (requester_id) REFERENCES public.profiles(id) not valid;

alter table "public"."friendships" validate constraint "friendships_requester_id_fkey";

alter table "public"."messages" add constraint "messages_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_receiver_id_fkey";

alter table "public"."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."sentences" add constraint "sentences_course_id_fkey" FOREIGN KEY (course_id) REFERENCES public.courses(id) not valid;

alter table "public"."sentences" validate constraint "sentences_course_id_fkey";

alter table "public"."user_courses" add constraint "user_courses_course_id_fkey" FOREIGN KEY (course_id) REFERENCES public.courses(id) not valid;

alter table "public"."user_courses" validate constraint "user_courses_course_id_fkey";

alter table "public"."user_courses" add constraint "user_courses_user_id_course_id_key" UNIQUE using index "user_courses_user_id_course_id_key";

alter table "public"."user_courses" add constraint "user_courses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."user_courses" validate constraint "user_courses_user_id_fkey";

alter table "public"."vocabulary" add constraint "vocabulary_course_id_fkey" FOREIGN KEY (course_id) REFERENCES public.courses(id) not valid;

alter table "public"."vocabulary" validate constraint "vocabulary_course_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url')
  on conflict (id) do nothing;
  return new;
end;
$function$
;

create or replace view "public"."leaderboard" as  SELECT id,
    username,
    display_name,
    avatar_url,
    total_xp AS xp
   FROM public.profiles
  ORDER BY total_xp DESC;


grant delete on table "public"."circle_participants" to "anon";

grant insert on table "public"."circle_participants" to "anon";

grant references on table "public"."circle_participants" to "anon";

grant select on table "public"."circle_participants" to "anon";

grant trigger on table "public"."circle_participants" to "anon";

grant truncate on table "public"."circle_participants" to "anon";

grant update on table "public"."circle_participants" to "anon";

grant delete on table "public"."circle_participants" to "authenticated";

grant insert on table "public"."circle_participants" to "authenticated";

grant references on table "public"."circle_participants" to "authenticated";

grant select on table "public"."circle_participants" to "authenticated";

grant trigger on table "public"."circle_participants" to "authenticated";

grant truncate on table "public"."circle_participants" to "authenticated";

grant update on table "public"."circle_participants" to "authenticated";

grant delete on table "public"."circle_participants" to "service_role";

grant insert on table "public"."circle_participants" to "service_role";

grant references on table "public"."circle_participants" to "service_role";

grant select on table "public"."circle_participants" to "service_role";

grant trigger on table "public"."circle_participants" to "service_role";

grant truncate on table "public"."circle_participants" to "service_role";

grant update on table "public"."circle_participants" to "service_role";

grant delete on table "public"."circles" to "anon";

grant insert on table "public"."circles" to "anon";

grant references on table "public"."circles" to "anon";

grant select on table "public"."circles" to "anon";

grant trigger on table "public"."circles" to "anon";

grant truncate on table "public"."circles" to "anon";

grant update on table "public"."circles" to "anon";

grant delete on table "public"."circles" to "authenticated";

grant insert on table "public"."circles" to "authenticated";

grant references on table "public"."circles" to "authenticated";

grant select on table "public"."circles" to "authenticated";

grant trigger on table "public"."circles" to "authenticated";

grant truncate on table "public"."circles" to "authenticated";

grant update on table "public"."circles" to "authenticated";

grant delete on table "public"."circles" to "service_role";

grant insert on table "public"."circles" to "service_role";

grant references on table "public"."circles" to "service_role";

grant select on table "public"."circles" to "service_role";

grant trigger on table "public"."circles" to "service_role";

grant truncate on table "public"."circles" to "service_role";

grant update on table "public"."circles" to "service_role";

grant delete on table "public"."courses" to "anon";

grant insert on table "public"."courses" to "anon";

grant references on table "public"."courses" to "anon";

grant select on table "public"."courses" to "anon";

grant trigger on table "public"."courses" to "anon";

grant truncate on table "public"."courses" to "anon";

grant update on table "public"."courses" to "anon";

grant delete on table "public"."courses" to "authenticated";

grant insert on table "public"."courses" to "authenticated";

grant references on table "public"."courses" to "authenticated";

grant select on table "public"."courses" to "authenticated";

grant trigger on table "public"."courses" to "authenticated";

grant truncate on table "public"."courses" to "authenticated";

grant update on table "public"."courses" to "authenticated";

grant delete on table "public"."courses" to "service_role";

grant insert on table "public"."courses" to "service_role";

grant references on table "public"."courses" to "service_role";

grant select on table "public"."courses" to "service_role";

grant trigger on table "public"."courses" to "service_role";

grant truncate on table "public"."courses" to "service_role";

grant update on table "public"."courses" to "service_role";

grant delete on table "public"."friendships" to "anon";

grant insert on table "public"."friendships" to "anon";

grant references on table "public"."friendships" to "anon";

grant select on table "public"."friendships" to "anon";

grant trigger on table "public"."friendships" to "anon";

grant truncate on table "public"."friendships" to "anon";

grant update on table "public"."friendships" to "anon";

grant delete on table "public"."friendships" to "authenticated";

grant insert on table "public"."friendships" to "authenticated";

grant references on table "public"."friendships" to "authenticated";

grant select on table "public"."friendships" to "authenticated";

grant trigger on table "public"."friendships" to "authenticated";

grant truncate on table "public"."friendships" to "authenticated";

grant update on table "public"."friendships" to "authenticated";

grant delete on table "public"."friendships" to "service_role";

grant insert on table "public"."friendships" to "service_role";

grant references on table "public"."friendships" to "service_role";

grant select on table "public"."friendships" to "service_role";

grant trigger on table "public"."friendships" to "service_role";

grant truncate on table "public"."friendships" to "service_role";

grant update on table "public"."friendships" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."sentences" to "anon";

grant insert on table "public"."sentences" to "anon";

grant references on table "public"."sentences" to "anon";

grant select on table "public"."sentences" to "anon";

grant trigger on table "public"."sentences" to "anon";

grant truncate on table "public"."sentences" to "anon";

grant update on table "public"."sentences" to "anon";

grant delete on table "public"."sentences" to "authenticated";

grant insert on table "public"."sentences" to "authenticated";

grant references on table "public"."sentences" to "authenticated";

grant select on table "public"."sentences" to "authenticated";

grant trigger on table "public"."sentences" to "authenticated";

grant truncate on table "public"."sentences" to "authenticated";

grant update on table "public"."sentences" to "authenticated";

grant delete on table "public"."sentences" to "service_role";

grant insert on table "public"."sentences" to "service_role";

grant references on table "public"."sentences" to "service_role";

grant select on table "public"."sentences" to "service_role";

grant trigger on table "public"."sentences" to "service_role";

grant truncate on table "public"."sentences" to "service_role";

grant update on table "public"."sentences" to "service_role";

grant delete on table "public"."user_courses" to "anon";

grant insert on table "public"."user_courses" to "anon";

grant references on table "public"."user_courses" to "anon";

grant select on table "public"."user_courses" to "anon";

grant trigger on table "public"."user_courses" to "anon";

grant truncate on table "public"."user_courses" to "anon";

grant update on table "public"."user_courses" to "anon";

grant delete on table "public"."user_courses" to "authenticated";

grant insert on table "public"."user_courses" to "authenticated";

grant references on table "public"."user_courses" to "authenticated";

grant select on table "public"."user_courses" to "authenticated";

grant trigger on table "public"."user_courses" to "authenticated";

grant truncate on table "public"."user_courses" to "authenticated";

grant update on table "public"."user_courses" to "authenticated";

grant delete on table "public"."user_courses" to "service_role";

grant insert on table "public"."user_courses" to "service_role";

grant references on table "public"."user_courses" to "service_role";

grant select on table "public"."user_courses" to "service_role";

grant trigger on table "public"."user_courses" to "service_role";

grant truncate on table "public"."user_courses" to "service_role";

grant update on table "public"."user_courses" to "service_role";

grant delete on table "public"."vocabulary" to "anon";

grant insert on table "public"."vocabulary" to "anon";

grant references on table "public"."vocabulary" to "anon";

grant select on table "public"."vocabulary" to "anon";

grant trigger on table "public"."vocabulary" to "anon";

grant truncate on table "public"."vocabulary" to "anon";

grant update on table "public"."vocabulary" to "anon";

grant delete on table "public"."vocabulary" to "authenticated";

grant insert on table "public"."vocabulary" to "authenticated";

grant references on table "public"."vocabulary" to "authenticated";

grant select on table "public"."vocabulary" to "authenticated";

grant trigger on table "public"."vocabulary" to "authenticated";

grant truncate on table "public"."vocabulary" to "authenticated";

grant update on table "public"."vocabulary" to "authenticated";

grant delete on table "public"."vocabulary" to "service_role";

grant insert on table "public"."vocabulary" to "service_role";

grant references on table "public"."vocabulary" to "service_role";

grant select on table "public"."vocabulary" to "service_role";

grant trigger on table "public"."vocabulary" to "service_role";

grant truncate on table "public"."vocabulary" to "service_role";

grant update on table "public"."vocabulary" to "service_role";


  create policy "Participants viewable by everyone."
  on "public"."circle_participants"
  as permissive
  for select
  to public
using (true);



  create policy "Users can join circles."
  on "public"."circle_participants"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can leave circles."
  on "public"."circle_participants"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can update their own status."
  on "public"."circle_participants"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Authenticated users can create circles."
  on "public"."circles"
  as permissive
  for insert
  to public
with check ((auth.uid() = host_id));



  create policy "Circles are viewable by everyone."
  on "public"."circles"
  as permissive
  for select
  to public
using (true);



  create policy "Host can update their circle."
  on "public"."circles"
  as permissive
  for update
  to public
using ((auth.uid() = host_id));



  create policy "Courses are viewable by everyone."
  on "public"."courses"
  as permissive
  for select
  to public
using (true);



  create policy "Users can delete their own friendships"
  on "public"."friendships"
  as permissive
  for delete
  to public
using (((auth.uid() = requester_id) OR (auth.uid() = addressee_id)));



  create policy "Users can insert friendships"
  on "public"."friendships"
  as permissive
  for insert
  to public
with check ((auth.uid() = requester_id));



  create policy "Users can update their own friendships"
  on "public"."friendships"
  as permissive
  for update
  to public
using (((auth.uid() = requester_id) OR (auth.uid() = addressee_id)));



  create policy "Users can view their own friendships"
  on "public"."friendships"
  as permissive
  for select
  to public
using (((auth.uid() = requester_id) OR (auth.uid() = addressee_id)));



  create policy "Users can insert messages"
  on "public"."messages"
  as permissive
  for insert
  to public
with check ((auth.uid() = sender_id));



  create policy "Users can view their own messages"
  on "public"."messages"
  as permissive
  for select
  to public
using (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));



  create policy "Users can delete their own notifications"
  on "public"."notifications"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can update their own notifications"
  on "public"."notifications"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own notifications"
  on "public"."notifications"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile."
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));



  create policy "Users can update own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Sentences are viewable by everyone."
  on "public"."sentences"
  as permissive
  for select
  to public
using (true);



  create policy "Users can update own course progress."
  on "public"."user_courses"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



  create policy "Users can view own course progress."
  on "public"."user_courses"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Vocabulary is viewable by everyone."
  on "public"."vocabulary"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();


